version: '3'
services:
  # Use admin:password to log in
  api-lb:
    image: haproxy
    container_name: api-lb
    volumes:
      - ./config:/usr/local/etc/haproxy/
    ports:
      - 9000:9000
      - 8080:8080
    depends_on:
      - api-a
      - api-b

  driver:
    build:
      context: .
      dockerfile: docker/Dockerfile.driver
    container_name: driver

  heavylifter:
    build:
      context: .
      dockerfile: docker/Dockerfile.heavylifter
    container_name: heavylifter

  api-a:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - 9001:9000
    depends_on:
      - postgres

  api-b:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - 9002:9000
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2
    hostname: postgres
    container_name: postgres
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
    - TZ=Europe/London
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=insecure

volumes:
  pgdata:
